git rm --cached 01/input.txt
git rm --cached 02/input.txt
git rm --cached 03/input.txt
git rm --cached 04/input.txt
git rm --cached 05/input.txt
git rm --cached 06/input.txt
git rm --cached 07/input.txt
git rm --cached 08/input.txt
git rm --cached 09/input.txt
git rm --cached 10/input.txt
git rm --cached 11/input.txt
git rm --cached 12/input.txt
git rm --cached 13/input.txt
git rm --cached 14/input.txt
git rm --cached 15/input.txt
git rm --cached 16/input.txt
git rm --cached 17/input.txt
git rm --cached 18/input.txt
git rm --cached 19/input.txt
git rm --cached 20/input.txt
git rm --cached 21/input.txt
git rm --cached 22/input.txt
git rm --cached 23/input.txt
git rm --cached 24/input.txt
git rm --cached 25/input.txt
