module Aoc04 exposing (..)

import Browser
import Html exposing (Html)
import Html.Attributes
import Html.Events exposing (onClick)
import Dict exposing (Dict)
import Array exposing (Array)
import Set exposing (Set)
import Array2D exposing (Array2D)
import Html exposing (text)

defaultDelay : Float
defaultDelay = 1

-- MAIN

main =
  Browser.element
    { init = init
    , view = view
    , update = update
    , subscriptions = subscriptions }

-- MODEL

type alias Pos = (Int, Int)

type alias Model = 
  { found : Int 
  , board : Array2D Char
  , highlighted : Set Pos
  , useSample : Bool 
  , lastCommandText : String
  , counter : Int 
  , debug : String }

initBoard : Bool -> Array2D Char
initBoard useSample = 
  let 
    sample = """MMMSXXMASM
MSAMXMSMSA
AMXSXMAAMM
MSAMASMSMX
XMASAMXAMM
XXAMMXXAMA
SMSMSASXSS
SAXAMASAAA
MAMMMXMMMM
MXMXAXMASX"""
    input = """SSSXSSMSXMMAXXAXMSSMSSMSXMASXXMXMMXMSXSMXMMSASXMMAMMMMMXSAXMAMASMASASXSXMMMSMAXMSAMXAAXXXAMXSAMSAAMMXASXMXXXXASXMMSMMMMMMMSMMSAMSSSMXSMMXSXM
MXMAMMMSAAMSSSXSMMMMMAMMMXMMXXAAXMAMMAASMSXMASAXSXMAAXAAAMAMXSXXMASMMAMXMAAAXXMASXSSMXAMSXMAMXXSMXXAMXXAXMSMMMMAAAXXAAAXAAAAXSAMMASXAMXXAMAS
XAMAMSAMMMMAAMAAXAAMSAMXSAAXSSSMSSSSMXMAXMAMSMXMAASXMSMMSXMMXAMXMASXMAXAMMXSSMAMSAMXAXMMAMXXXXXMASXMMASXMAAXAASXMASXSSSSMSXSMXAMMMMMMSSMMSAM
SXSASMMSXAMMSMMMSSSMSXSASMSXMAMAAXAAASXMASAMXASMSMMAMSMXXASMMSMXMASMSSMMXSAAMASXMMMASMXMAXMSASXMAMMMSXMASMMSSXSXXXMAMAMMAMAMASMMMMAAAAXAAXXS
MXMXMAXXMXXAAAXAAAAAXAMAMAMMMAMMMMSMMMASXMASMXMAXXSAMMMMSMMAAAAAMMXAAAASAMMSMAMASXMAMMXSSSMXMSAAAXAMXAXAMXMAXMMMXSMAMAMMAMMMXMMAASMSSMSMMMMA
MASMSMMMSMMSXMMXMMMMMMMSMAMSMXSAMXAXXSXMAMXXXXMXMMXMXSAAXXXMMSSXSAMSMSMMASAXMASXMAMMXSAMXAXXXSXMMSSSSSMXSXMASXMMAMSSSXSMMSASXAXSMMXAMXMAAASM
SAXXAMAAAAMAASXMSXAXXSAMSSMMMMSAMXXMASXMAMSXMMSSMMSAASMMSMMSAMMAMMMXAMXSAMMSSXMASMMXAMASXMMMMMAMXXAAAMAMSXMMMMMMAMAXMAMAMSASXSMMASAMXAXXXXMX
MXSSMSMSXSMMXMAAXXAMAMAXAXAASAMXMXMAXXMMAMSAMASAAAMMMSXMAMAMASMXMSMMXMAMXSAMXMSAMASMASAMAAAAASAMXMMMMMSMSASAXAASMMSXMAMAMMAMAXXMAMXSSMSMSSSX
XMAAASMMAMAMSSMMMMSSXSMMMXMMSXXMSMMMSMAMSMSAMSSMMMSMMSXMXMMXXMMXAASMAMAMAMMMMMMXSAMAXMMMAMXSXXAXSMMXSXAAXAMASMMAAXAASASAMXAMMMSMAXAXAAAAAAAM
MASMMMAXAXAMXMASXXAAMMAAXMAMXXXAAAAAAXMXMASAMXMAMXSAMXASAMXMMASMSXMMXMAMMMXMAMSMAMSMSAMXSAMXMMSXAXMMMSMMMMMXMAASMMXXMAMMSSXSAASASASXMMMMMSMA
AMAMXSAMXSSMMXMMMMMSSSSMSAMSASMSMSMSSSXSMAMMXSXXMAXAXSXMXXMASAXXMMSXXSASMSSSMMXAMMSXMXMAXAMXAAMXAMXAMASAAXXXAXMAXSXSMAMXAMASMAMAMAMXMMXMAXAS
SSXSXMXMXSXAMXSAAMXMMAAXAXXMAMAMXMMXAXAXMXSMAMMAMSMSMMMMXSMMMAMXMASAAXAMAAAXMASMXMSAMSMMMAMMMMMAMXXMMAXMMMSMSMSXAXAMMMSMASAXMAXAMXMAXSAMSSMX
XMAMMSAMMSSSMAMMSMAMMSMMMMXMXMMMASXMXMXMAMAMMSMSXASAAAAMMMASMMMAXSMMMSSMMMSMSAXMASMAMAAXSSMXMASMMSSXMMSSMMSAAAXMMMAMAAAMXMMSXMXMXXSAXSMMMSAX
MMSMAXASMXAMMXMAMMAMXAMMXMXSAAASASAXMASAMSSSMSAXMXSMSMXSASAMAASMMMAMXAXMAMXAMMMMXMMAMMMAMMAMXASAAAMASAAMAAMSMSMMXMASMSXSXAMXMMASMMMXXXXAAMMM
XAASMSMMMMAMAAMASXMSMSAMAMMXXSXMASMMMSASAAAAAMMMMAMXMAAXMMAMMMSXAXSMMXXMMAMXAXSASASXSXMASMXMMMSMMMSAMMSSMMMXMAMMAMMSMMXAMXMAMSASAMAXXMSMSMXA
MXMSXAMSXXXMSXSASAXMAXMSASXMMMXMXMMAMAAMMMSMMMXSMXSAMMMMSMXSAMXXSXMASASXSXSXAASAXASAAXSASXSXMAXAAXMXSXMAMSASMMMSASMSASXMSSSMMAAXMMMSAAXAAXMX
SMMXMAMAMSAMXXMASMMMAMXSASMAMAXMAMMSSMXMAMXMXMXMAXMXXSAMXAASXXMAXXSAMMAAMAMMAMMMMMMMMMMMSMXAMSXSMXMMXASAMXMXAAASMSAMXMAMAAAXMMMMXMAXMMMMMMSA
SAMAMSMMAAASXMMAMXAXAXMMMMMSMAXMAMAXAXMSAMXMASXMSMXMASXSMMMSASASXAMASXMSMAMMXMAXAXXXXASXSAMSMMAMAASXMXMAMMXSSMMXAMAMMMMMMXMMMAMMAMSSSMSAAAMX
SAMMMAASMMMMMAMSSMSSSSMSSMSXMAMSAMMSSMMXAXAMASAXXAAXXMMMXAMXAMAMMAMAXAXXXSMMASMMSXMXMSMAMAMXASAMSMMAXSSMMMMMXASMMMASAAMXSAAXMAMXAMAAMASMSXXS
MAMXSSXMSMSAMXMAAMMAMXAAAXSAMXMMAMXAMXAXSSSMSSXMMSMSMAASXSSMAMAMASMMMSMMMMASASAMXAAAMAMMMAMMAMSMXMMSMAAXSAXXMASAMSMSMMSAXSXMMASXSMMSMAMAXMXS
SMMMXMAAAXSASMMSSMMAMMMMSXSXMAMSAMMAMMMMXAXXXMAMAAMXMSMSAMXMASASMXAAAMMSASMMAMAMSXXXSASXMAXMXMASXXAAMSMMSMSMSMMAMXASAMMMMXMAMMSAAMMAMXSAXAMX
AASXAMMSMXSXMAAAMXSSMMSAMASMSSXMMSSSMSXSMMMXMMAMMXMAMXAMXMAXXXASXXAMXSASXSASXSSMMMSMAASXSASMMMAMMMSSMXAAXXAMAASMMMXMAMAXAMAXSMMXMMSASMMMXSAA
SXMXXMAAMASMSMMMSAAAMASAMMMXAMASXMAXAAMXAXAASMSXSAMSSMMMSXSSSMAMMSMMXMAMAMXMAAXAXAAAMMMMMAXAAMASAAMAAMMMSSXSSMMAXMASXMMMSMMAAXMAXMSASXAAMMSS
MASMMMSXSXSAXXXXMMSSMAXAXSXMMSAMAMSMMMMXMMSMSAAAXAMAXAXAXAXAMMSMAAMMAMAMSMMMXMSMMMSXXMAXXASXSMASMSSMMSXAAXXAMXSXMAMXMAMAAAMXXMSXSMMMMXMXSXMX
XAMXSAMXAAMMXXAAXMAMMMSSMMMSAMAXAMXAXASAXAMAMMMSMXMMSSMSSMMAAXMMMSXSASAAAAMSMXMASXMXSSMSMXSAAMAXXAAXAAMMSSXMAXMMMXSMMAMSSXSMAAXXAXAXMAMSMAMM
MSXMMASAMXMAAMSMMMAMSAMXAAAMXSMMSSMXSASMMMMAMSAMXMSXMAAAAXSAMSMSAMMMXMMSSSMASMMASAMAXAMXMAMMMMSXMSMMMSASAMXMAMXAMXSASAXMMAAXMMSAMMSSSMSASAMA
XMASXMMMAMXMMXAAXMAXSXXSXMMSAMXAXAXAMMMXAAMAMMMMAMXASXSSSMSAXAAMASXSASMAAAXMSXMASAMXSAMXMMSXMAXMAMAMXAMMASXSASMXSASAMXSAMAMXMAXMXAMAMXXMMMXS
ASXMASAXSMMSMSSXMMMXMMMSXSASMSMSMMMXSAXSXSSMSAMSAMXXMAMAAASASMSMMMASASMSSMMXSAMXSAAMXMAXMXSASAMXASXMSXSXMAASAMAXMAXXMASAMMXMMXSXMXSAMSMSMSAX
MXASAMASXAAMMAAXSASAMXXSAMASASAMAASASMMMSMAAMAMSMMSXMAMAMXMXSMMXAMXMSMMAAXAXSASAXXMXAMMXMASAMXSMXSAAAMXMSMAMMMMMMSMMMXSMXSAAXMMAMXMAMMAAAMAS
SSMMXMXAMMMSMMSMSASXXSMMAMMMMMAMSMMASXXMAMMMMMMMMMAAXMASXXSASASAMXXMXMMMSMSASAMXSAXMASAAMASXSXMXAXMMMXAXXXMSASMSAXAXMAMXAXMSMXSAMAXMAMXMSMAM
XAMAMSSSXMAMAAXAMXMMMSASMMMSXMXMXAMSMAMMXXAXXAAXMASMMMAMMMMASAMXMMMSASAMXAXMMAMSAMXMAMXSMMSXMASMMXXXXMMSXSAMXXAMASXMMSSMMXMAMXMASASXSSSMMMAS
MXMAXAAMXMASXMMSMMAXAMXAAMXMASMXSAMMMSMMAMSSMSSSMXMASMAXSAMAMXMAXXAMMSASMXMXMMMXMASMASXMXXSASXMAMASXXAAXMASXMMMMMMMMAAAAAAMMSXSAMASAMXAAXSSS
MSSSMMSMXSXSAAAAMXMMMXMMMMAXXMMASAMXAAAMAXAAAAAAAXSMASXXSASAMSSXMMMSASAMMSXSASMXAMXSASAASMMMSAMSAASASMMXSAASAAXAAAXMMSSMSMSASMMXSAMMMSSMMMAM
MMAAMXXAMXAMMAMXMASASASAXSSMSAMASMSMSSSMMMSSMMSMMAMXMAMASXMXMAMMAAMMMMXMSAASAMAMSAXMSSMMMXAAXAMAMXSXSAMAMXXXMMXSSSXSAMXAAXMAMAMASAMXAAXMASAM
ASMMMXMAXMAMXXSXMASASAXXMXAASAMASAMAAAAXMAXAAAXMMMSAXAMMMSMXMASXMXMAMMMMMXMMAMAXMASMAXMSXSMSSSMAMXMASAMASXMSXSAMAMXASXMMMXSXSAMXXAMMMSSSMSAS
MMAXSXMXSSMSSXSASMMMMMMSMMMXMMMXMAMXMSMMMSSMMMMXAAMMXMXAAXMASASXASXMMASXMMSMXMMMAAMMASMXAXAAXAXAMXSASMSAXAMAASXMSMSSXMXXAAMASXSXSSMSXMAAASXM
XSMMMASAMAAAAAMAMAAXMAMXASXMAXSASMMSXMASAMAMSSSSMSXXAXXMSSMMMAMMXMAXMMXAAAMXSASMMMSAASAMXMMMSMSSSXMASAMXSSMMMMAAAAXXXSMMMSMAMAMXAASMAMSMMSAX
MMMXXAMXSMMMMMMSMMASXMMSXMAMAMXAMXAAASAMXXAMAAAXSAMSMSAMAMAMSSMSXMAMSSSSMMSASAMAASAMXXMAMXAXXXAAXMMAMAMAAXXXAMMSMMMMMAAXAXMXMAMMMMMXXMXMSXMS
AAMAMSSMMMMSXXXXAXASXSASMSMMXSMMMMASXMSMXMSMMSMMMXXAASXMAXAMXAASAXMASAAXMXMAMAMSMSMSSSXSASMAAMMSSSMSSXMMSSMSMXXAXAAAMMSMMXMAMMSMSMSSXMAXXAXX
XAMAXMAAXMASAMMSXMMSAMASAAXXAAAASXAXMAXXMAMAAMAMSMMMMMXSSSXSSMMMAMASXMXMSMMSSSMXASXAAXAMASMXMMAAXAAAAAXAAMXAMMSMSMSMSAMASASAMXAAAAMMMSSSSMMM
SSSSSXSMMMAMMAAAAXAMXMSMXMSMMSSMSMXSMAMMMMXMMSAMXXAXAMMMXAMXMAMXAMXMXAMMAAXAAAXMAMMXSMSMAMASXSXSSMMSSSMMMSSMSAXASMXAMAMAMXSXSSMMMSMXAMMAXAAX
AAAASAAMMMSSXSASXXMXMXXAXMXAAMXMXXMSMAMXAAMSASXSMSASASAMXMMXSAMSSSXSMSMSSSMMSMMMMSAMAAXMAMXMASXMXMMMAXXAXXMXMXSAMMMSMMMSMMXMAXSASAMMSSMAXSXS
SMMAMMMSAAXMAXAMAMXASAMMMMSSMSMXXMAXMSMXMXXMASASAMASXMXMASAAMXXSAMXXXAAAAAXAAAAAAAXAMMMASMXMXMMSAAAMMMSMMXMXAAMMMXAAXMAMASMMAMMXSASAAAMMMMSM
XXMXSXAXMMXSAMMMAXSAMAAMAMMAAAAXSXMMAMASXSMMAMAMSMAMAMSSMSAMMMMMMXMAXMMMXMMSSSMMSSMMSXSAMMAMASASXMXMXMAMMSSMSAMXAMMSXSAMSMAMSSSXMXMMSXMMAXMX
MXSASMMMSAAMXXXSXMMSSXMASXSAMMMMMAMSAMXMAAXSXMXMXMASMXXAMXAXXAAAMASMSSXSAMXXXMXXMXXXSAMASMASAMXXMSSSMSXSAAAMAAXMASMAAMXMMSSMAAAAXSMMAXMSMSSS
SAMXXAXAMMXMXAMXXXAAMMMMAMXAXMXAMXMMAMAMSMMXMMASASMSXMSAMSXMSSSMSASAAAAXXMXMASXXMAMXMAMXMXASXSMSMAAAAAAMMSMMSMMMAAMMMMMAMAXMMSMSMSAMAMXAAAAX
MASMSSMMSSMMSMSAMMMSSSSSSMSMMMSSSSXSAMXMMXMAAXAMXSXMAMSMMXAMMAAAMXMMMMMMXSASXMSAMSMXSMMXSMMSAMXAMMMMMMSMMAXMAAMSAMXMXAAXMAXSMMAAASAMAMMMMMSM
MASXAAXXAAAMAAAAMAXXAXAAXMAXAMXAXAASXSSXXASMSMMSMXMMSMMSMSSMMMMMSXSSXXMAMMAMAMSXMASAAAMMMSXSMMSMSXXXAMXXSXSSSXMMMMAMXMSXMAXXAMSMMXXMXMAXAAXA
MASMXSMMMSMMMMMMXXSMMMMMMSXSSSMXMMMXMAXASMMAAAAAMXXAAAXXMAMMAASASAAAXXASMMSMMXSXMAMSSMMSAXMXAASAMASAAMSAMXXXMAAXAXASASAMMSMSAMMXXXXMASMSMSSM
MASXAXAMAXAMXMMMMMMXAAXAAXMAMAMXXXMASAMMMAAMMASMMSMASMMMMSSMSXMASMMMMMXMXAMAXXMAAAMXXAAMASMMMMSAMAMSSMMAXMXASXMSSSXSMMASMAMMAMXAXSMMMAMAMXAX
SAMXXSAMASAMMMSAAXMASASMSXMMSMMMSMMAMAMXSXMXXXMXAASAAMSAXAAXXXMMMXAAAAAMMMSXMASXMMSASMMMMAAXAAXXMXMAXAMSAMMMAAMAXXMMXMSMMASXMMMMMSAAMASAMSAM
XAMAMMAMMMAMXASXSMXAXMSXXASAMAASAMMSMXMAXXMSXXAMMMSSMAXXMSSMSSSMMSSSSMXMAMAXSXMXAXMMMMSSSMXSMSMXMAMASXMXAXAMXAMASMXMAXMASXSAXSASASXMSMSMAMMM
SSSMMMSMSXSAMXMMXMMASAMASXMAMXMXASXAASMMSAASMMXMMAMAXMSSMAXAAXAXXXAAAXAASMMMMAXMMMMMMAAXAXAXAAXAMMSMXMASMSMSMSSXSAASMSSMMSMMMSAMASMAAAMAMXSX
AMAAMSMAMMMMSSMMAMMMMAMAMMSSMSMSMMMMXSAMXMXXXXAAMSSMMXAXSAMMMSMMAMSMMAMXMASXXMSXMAXAMXSSMMSSSMSSXXAMAXMMAMASAAXAXXXSXAAMSXSAAMAMMMASMSSSXMAS
MSSMMAMAMAXAAAAMXSASMXMASMAMAAAAXAXXAMAMXXMAXMXMXMAXSMMMSXSXXAXMMMAAXMXMSXMAAXMASMSMMAMAAAAXAAAAMSASXSMMXMAMMMMXMXXMMSMMAASMXXAMXAXXAAAAXSSX
XAMXXXXAMSMMSSXMMSASXXXXXMASMMSMSSSMXSAMMAAXSMSXMMMMAAXXXAMASXSAXSMSMXAAXSXSMMSAMXAAMSSSMMSMMMMSMMMMASAAAMXSAAMMMMMMMMAAMMMAMSMSSSSMMMMSAMXS
MMSMSSSMSAAMAXAMXMMMMMMMAMASAAXAAAMAMSMSXSSXAAAASAMXSMMMMSMXMASMXMXMAXMXAMMASAAAMSSSMAAASXMMSAAMMAAMXMASXSASXMSAMAAAMXXMSAMAMAAAAASXMXAMMSAX
AXMAAAAMSMSMSSSMSASAAAXAAMSSMMMMMSMAMMAMAMMXMMMXMASAMAAXAAMAMXMXAMSSSSXMAMSAMXXAMAAXMMSMMSXASMSSSXMMAXXMAAMMMXXAMMSMSAXMSASXMMSMMMMMMMXSXMAS
SMMMMSAMMAXAAAAAXASXSSMSXSAMXSAAAAMMXSAMAMSAMASMSMMMSSMSSSMMSASXSAAAMAASAMMASMSSMMSMXXMMAMMMMMMMAASXMMAMXMMSSMSSMMXMAXSASAMMXXAMXMASAMMMAMMM
MXSAMMXSMMMMMMMMMXMAXAMXMMMMMMMXSMMXAXASXMMASASAAMAAMAAXXMASMXMAMMMSMSMMAMSXSAAAXXAAMMAMSSXAAXAMMMMASXAMASAMXAAAMMAXAAMAMXAMMSASXMASASASASAS
SASMSXAMASAMAXAAMMMMSMMXMAAAAXXMMXSXASMMXSSMMMMXMSMMMMXMMMXMAAMSMXAMXMAXAXMAMMMSASXSXSAMAMMASXMSMMMAMSMMMMMXMMMSSSSMMSMXMMXSXSMMXMMSXMASASAS
MAMAMMMSASASMXSAMXAAAAAMSSSSSXSAAAMMMMAAAMMMASMXMMMSAMXMXMAMSMSAXMMSAMSSSSMAMAXMASAAASAMAMXMAMXAAAMXMAXAXAAAMAAAXMAAXAAAXXAMAXXAAMASAMAMAMAM
MAMAMAMMMSMMMMAMXMMMXSMAXMAAAASMMASAXSMMMSMSASAMXAASAMXMSSXXAXXMAXXMASXAAMMMXMSMXMMMMMMSSSSXSMSXMMMXSMSSMMSXSAMXSSSMMSSMMMAMAXMSMSASXMSMSMSM
SMSSSMSAMMMAXSSSSMXSXXXMAMMMMMMMSAXAMMAAAXXMASASMMMSAXAMMAMSXMAMSMSSMMMMMMAXASAMXXMMXSAAXXMAXASMSXXMAMAMAMXMAMMXAXAMXMMAXXSMMXXAAMMMAAMAMAAA
AAAXAXSAMAMMXMAAAXAXMAMSSMMMXMMMMXXSASXMMSAMXSXMAAXSXSSSMAMMMSMAAAMMMAXXASMSMXASMMSMAMMMMMAMMAMASAASAMASMMXMAMMXMSAMXSMXMAMAASXSSMMSMMMAMSMS
MMMSMMSXMSSMAMMMMMMSMMMXAAAXAAAASMXMASAAMXASAMXSSMXXMAXXXASAMAMSMMMXSAMMXMMAXSMMMAAMMSMSASAXMSMAMXMMASAMXAASASXAXAAMMSAAMAMMMSAAXXAAAXSMMMAM
MSAMXASAMXAMSMSAXAAAAAXSMMMSASMXSAAMASMMMXAMXSAMASXMXSXMMXSMSXXMMMSAMXSMAXSAMMAAMSSSXAAMMMSMSXMSSMMSAMXSMSXSAXMASMSMAXMXMXSXSMMMMMSSSMXSAMXM
XAAAMMXMMSXMXASASMXSSMMAAXXAXXXAMXMMXMMXSAMXMAXSAMXMMMAASMSAMMMAAXMASAAMAMMASXSXMMXMMMSMSAMXAXSAAAAMXSASMMAMAMXXAMXMXSMXSAMXMAMXSXMAMMAMMSAM
SSSMAMXSASASMMMXXXAXMMMSMMSMMSMAMAXXXAAAMAXSAXMMMMASAMXMSAXAXSSMMMSAMMAMXMXXAAMMMMAAMAMAMXSMMSMSSMMSAMMSAMXMXMMSSMXMASXAMASAMAMAXAMMMMSXXSXS
AAAXXXXMASMSAMMXSAMXAAAAAAXAAXMASXMASMMSSSMMMXMAAMAXASXXMMMSMXAASXMXSAMXMSMSMAMAASMSSMMMMSXASMAAMAAMXMASXMMXMXMAMAAMASMAXXXMXSMMSMMXAAASAMXM
MMMMSSMMMMXSAMSMSMXMSMXXMMMMMSSXSASXMMXMAXMASAXMSSSSSMMMMASXSXSMMAMXMMMAMAAAXASXMMAMXAAAMASMMMMMSSMSASMSAXMASAMAMMMMASXSASXSAXXXAMMXMMSAXMAS
XSXAAAXXMXAMAMSAXAAAXSSSSSMMSAXAMAMAAAAMMMSAMXSAAAAMMAAMSXSAMMMXXAMAXXXSSMSMSXSMSMAMSSMXSAMXASXMXMASASXMMSSSSXSAMASXMMMMMMAMASMSASAAMXMASXAA
AMMMSSMAXMMSSMMXMMMXMAXAAXASMSMMMSSSMMMXSAMAAAAMMMMMMMMXSAMXMAMASASXSXXMAMXXMXMAMSSMAAAXMASMXMASAMXMXMAXXAXAXMSAMMXAXXAXAMXMXMASMMMMSAMASMXM
MXSAMAXMXAMAXASXSXSXMMMMMMMMAMSXXAAMXMSAMASXMAXMAXAAXAXMSAMXMXSAXXAXAXSXXMSXSAMXMAXMMMMMSAMMMSMMMMXAMXSMMSMMMXSMMSSMMSSSSSXMMMMMMSAMXMMASAMS
SAMASAMMSMMMSMMAXAMAXXXAXMXMXMAMMMMMAXMASAMMMAMSMSMSSXSAMAMMXXMMSASMMMSAAAAASMSSMSSMSMSXMASAAAMASXMAXMAMAAAASXSMAAAAMAMAAXXAAAAAXSXMASMXMMAA
MAXMMMSAXAAAMMMSMMSSMMSSSMASASAXSXSXXMSAMMSMXAXAASAAAMMAMAXMMAAMAXXSAAMSMMMXMAMMAMXAAASXMASMSXSAXSAAASAMMMMMSAXMMSMMMXMSMMMSSSMSMMMAMXMAXMSM
XAMSAMXAMSMMSMAXAMAXAAAAAMASAXXMSASXAAXMXMAMMMSMSMMMSMXASXSMMASMMMAXXSMMMXMAMAMMXMASMSXAMAXMMXMMSSMMMSASXSSMMMMMXAMSXMAAAXXAMMXXMXXAMXMSXAXX
MMXSASMMMXAAAMXSSMAXMMSSMMMMMMAMMAMMMMMMASASAAXMAMAAXMSAXAAMAAMAXXAMXXMXMAXSSMSMAMXXXMXXMSSSMMSMAXAMASMMAMSAAXAXMASXASXSSMMAXXXMAMSASXAXMXMX
ASAMMAAASXMSSSMMMMSSSMXMXXSASMSMMXMXMXXSASASMAMSASMXSASASXXMMSSSMMAMSASXSXSAMMAMAXAAAXSXMAAAXSAMSSSMASAMMMMMMSMSSXMMMMAAXASAMSMXAMXSSMMSAXAM
SMASMMSMAAMAMXAMAMXAMSAMXMMASXMASMMSXAMMXMAMAXXMXSMXAMMAMXAXMXAXAXAMMAMAAXMAMSASMSSXSAMXMMSMMSASMAAMAMMSXSXMMAMAXAMXAMXMXXMAMSAMXSXXXAAXAMMA
XSAMXAXXSSMMMSMMMMMMMSXMASMAMASAMMAMAMMSSMMMXMMSAMXSMXMSMSMMSMMMXMAMMSMMMMSAMMASAMXMMMMSMAMXASMMMSMMSSXSASXXSAMASMSSMMASXXXXMMSMAXMAXMMSMSXS
AMMMMMSAMXAAAAMMMSAMXMASMSMSSMMMMMAMXXAAXAXMASAMMXAMXAAMAMXAXAMAMSAMAXAAAMMAMMAMMAAXXAAMMSSMXSAAXMXMXMAMAMAXSAMXXXAMXSASMMSAMAAMXSMSMMMAAXMM
XMASMAMMMSSMMMSAAMSXXAMXXMAMAAMASXMMMMSXSSMXXMSSXMXSSXSMMMMMSSMSASASASXMXMSSMMSMXMMXSMMSAMAMXSXMMSAMXMAMAMSMMAMAMMMSMMAXAMXAMSSMMMAAAASMSMAA
MSAMXSAMAXXAMAMMXMMSAMXMAMASMMMAAAAAXAMXMASAMXAXMASXXSXMASAMAXAXMSAMXSMXXMAMAAXMMMXMAMXMXSAMXMAMAXXXAXMMSXXASMMXSAAAXMSMXMSXMXMAAMMMSMXAMXXM
MMSSXMAMMSSSMXSAXSAMXSAMASXSMAMMSSMSMSSXSAMXMMMSXSXMMMSSXSMSASXMXMXMMMXMAMASMMSSMASMSMSAASXMASAMXSMMSXSAMXMMAMAAXMXSMXAAMMAAXAMSXMAMAXSMMSMS
SAAMMSAMAXAXSXMXXMASASAMAMAXXAMMMMAAXXAAMAMAASMMMMAMAAXXXMASAMXMXMMMAMAMXSASAAAAMSMAXAAMXSMSXSASXAAAAAMXMAXXAXMMMSAMXAMXAMSMMMXAXMXSAXMXMAAM
MMXSXSAMXMMMMMMMMSMMMSAMSSMSXSMSAMSMSMMMMASAMXAMAMXMAMMXXMAMAXXXAAAXAXXMAMMSMMSXMAMMMMMSAMAMASAMXSMMSSXMMSSSSMSAAAASAMXASXXAAMAMMMAMMMMAMMSM
SAXSXMXSAMAAAAMAAAAMXXAMXXXSMMAMXMAMXXMASXSAMXXMAXMXMSMXXMXSAMSSMSXSASMASMMXXXMXSSSXAXAXAXSMMMMSMMMXAAXMAMXAMAMMSSMMMMSSMMXMMSASAMAMSASXSMXX
MXSXAMAMMSSSSXSMSSSMXSSMSMXSAMAMAMAMSMMXXXMXMASMSMSAAAMMXSAMASXAAMMMMAMXMAMASMMMXAMAMMMSMMXXXXAAAASMSSSMASMMMSMAMMMXAAXAAAMSASAMXSAMMASAAXAX
MMSXMMASXMMAMMAAAXAMAXAAAXAXXMAXMSMMMASXMMSMMMSAAASMMMASAMASXXXSMXXMSSMASAMAXAASXMMSAAMAMAMSMMSXSMSAMAMMAMXMAXMSSMXMMXSMMMSMAMAMMMMSSMMXMMSX
XAXAXXXSAAMAMXXMXSMMSSMMMMSSSSSSXAMASAMASAAASXMXMMMXASXMASAMXMXXAMSXMASXXAMXSSMSAXAAMXSAMMAAAAXXXMMAMAMMMMAMMXAMAMSMSXXAAXXMXMAMAAAXAAAXXXMM
MSSXMASXXMMASXSAMXMAMMAAXXXAXAXXXMSMMASXMMMXMAAMXASMMMAMAXAXXMAMXMMASXMMXSAMXMAXMMMXXMSMSMSSMMSXMAMXMASAXSASMMMMMMSAMASXMMSSSMSSMXMASMMSSMSA
AXAAXXXMAXSASMAMSAMXSSSMMMMXMXMMAMAXMAMAAAMSMMMMSMSMMSAMSMMSMMAXAAMAMAMAAMAXSMXMXAXASMSAXAXXXXMAMSSMSXMAXXXAMXMASAMAMAMAAAXAAAAMXAMAXAXXMAXS
SMSAMXMASMMMMXAMMXXAMMMAAASMMSASMSXSMMMSMMXAAAXXAAXAASXMMAAAASASMXMMMAMMASMMMXMASXXXMAMMMSAMMMSMMAAXSAXSASXSAMXXMMSMMXSSMSMSMMMSSSSMSSMMMSMX
MMAMXSMAMAAXXMXSASMMSAXSMSAAASAMAXAMXMMXXMMSSMXSMXMMMSXMXMMSXMMSAASMSXSMAAMAXMAXXXASMSMXMMAAAAAXMMMMMXMAAAAXXSMXXMAMXMMXAXAXAMXXAMAMXAXXAMMM
MXMSSSXAMSMMAMMSAMXXMXXMMMMMMMAMAMXMXSAMASAXAMXXMSXSAMAXSAAMASAMXMAAXAXMMSSMMMMXMMXMAXAMXSSMMSMSMSAXXASMSMAMAAXMMSMSAASMAMSMASAMXXXMSMXMMSAA
SAMXAMSSXMSMAXAMMMSXMSXSAXAAXSSMMXSAMMAMAMXSMMAAAAXMAXMMAMXSXMSAMXMAMXMXAAAAAXSAMAAMSMSSMMAMMAAAAAAMSMMXMMAMSMAAAMXSMSXAAXASAMMSSXMAXXMXAMAX
SASMXMAXAASMMSSMSAMAMAAAMXSMMAAAAAMAMSSMMSAMXSSXMMXSMMSSMMMMXXXMASXSMAMMMSMMMXMASXXXAMXAXMAMSMSMSMSMSAMAXSXMASAMXXASXMMSMSMSXMMAXAMAXMAMSSSX
SAMXAMASXMMAMXMAMMXAMMMMXAMXMSSMMXSSMAAAAMASXMMSAXXXMAAAXXAXXAMMMMMXSAXAAMXSMSSMMMSASXMXMXMXMXAXXXAASMMMXMAMXAMXSAMSAXAAMMAMXSMSSXMASASXXAXM
MMMSMXAAAMSAMMMAMSMSSSMMMMSAXAMXMXSAMSSMMSSMMAASXXAAMMSSMSXSMXMXAAMMSXSXSMASAXXAAASAMXMSSXMAMXMASMMMMXXMAXXMMXSAXAMSMMSSMMAMXAAAAAXAXMMXMMMA
AMAMAMSSMMAMMXSSXSAXAMXAAAXMMASMMMSAMAAAAXAASMMSSMSSMAXAAXAXXASMSMSASMSAAMAMMMSSMMXAXXMAMMSMSAMAMASXMAXSSMMSMAMXSMMXXAXMASMSMMMMXSMSSMMAMMAX
XMAMXXMAAXXXMAMMAMXMASXMSSSMSASAAASXMSSMMSMMMMMXMXAMMXSMXMMMMXSAAXMXXAMXMMXXAMAMXXMSMSMAXMAASAMAXSMMMSXMAASXMASMMAASASMSMMAAAXASXMAMAASXSSMS
MSSMMASMMMMMMAXMMMSXXMAMAAAAMASMSMSMMXAMAXXAXMSAMMMSSMMMAAAXXXMXMMSMMSMSMMAMMMMSSXMMAASMMMMXSXMSXXMSAMAMSMMASXSAMXMSAMAAMSSMSMAMXSSMSMMAAAMX
XAAASMMXAAASMSSMAAMAMSSMMSMMMXMAMAMAXXAMMSSXSAMASAAAMAASXSMSSMMAXAAAMXAAAMSSMAAAMAMMXMSXMSXASMMMAMAMASMMMASXMASMMXXMAMSXMAAXXMXSMXAAXXXMSMMM
MMSMMAMSMSMSAXAXMSSMMAXAXXMXSAMAMAMSAXMMMXAMXASXMMMSSSMSXXMAAMSMMSSSMMMMMMAAMMMMXAMAMSMMMSMMMAAMMMAMASXMMAMASXSAXXASXMXMMSSMXMXMAXMMMXXXMAXX
MAXAXXMAAMXSMSMMMXXMXXXMMMSASASXSMXMMASAMXMASMMMMAMXXMASMSMXSXXXAXXAAMXAMXSMMXAXSMSASAAAXXSMXSMMAMXSXMAXMAMXMASAASMMMAMXAAMMSSMMMMAAXXXASMMS
MSSMMSMMSMAMMAAAXXXMASASXMMASAMASMXSXMSASASXXMMASAMXAMXMAAXSAXMMSMMSMMSSSMXSASXXAASXMMSMSSXSAAMSSSMSMSXMMMSMSXMMMSAASXSMMMSAAAAAXSSMSSMMMAAM
XMAXAAASAMMSMSXMMMASASAMXAMAMAMAMXXMAMMMMAMMAMXMXMSSMMAMSMSXAAMMASXMMAXAAAMSXAXSMXMASAXXXXAMSSMAMAAMASMSMAAAXXAXASAMAAAMSSMMSSMMXMAMAXAASMMX
XSAMXSMSASAAAMSMXSAMXSXMXSMSSSMXXAMSXMASMAMSSMSXSAMXAAAMAXXMMMXSAXMAMXSSMMMSXMASXAMXAASMMMMMMXMMSMMMMMAAMMMSMMXMASMSMAMXMASAXAAXAXAMXSMXSXSX
MMMSAMASXMMSXSAMXMASXMMSAXXMAXAMMMAAASASMSMMXAAAAXXSMSMSMSMAMSAMXXSAMXMXAMAXAXMMMXMAMSMAAAAAXMXMXXXAMMSMSMMXMMAMXMAXXXMASMMMSSMMMSXSASXMMAXS
MAASASAMAMAMMSAMXXAMXAAMASAMMMMMAMXSMMASMMAMMMMSMMAXAAAAAAMAMMASAXMASXMASMMSASASMSMAXAXSMXXMMXMMMMSMSAMMAASXMSMXAMSMMMSASXAMXMASXAXMAMASMMMX
SMMSMMAXXMAXAMMXSMMSSMMSXXAMXASXMSAXMSXSASMMAXXMASXMSMSMSMSSMSAMXSSMMAXAMXXAASAMAAXAMSXMASXSSMSMAAAXMASMSSMAAXAASXMAMAMASMXXXMAXSSXXAMAMAXAA
ASAMXSXMMSMSMAMAMXAAAXXXXSXMSXSAAMAMAMASAMXSSSXSAMMXMAAXAMXMMMMSMXAASXMMMMSMMMXMSMMXAMAMAMAASAAMSSMMMAMXMAXMMMMMMASXMAMAMMSXXMSXXMAMSSXSMMSA
AMMXMASAAAXAXAMMSSMSSMMSMSMASAMMMMAMXMAMAMMAMXAMAMXAMSMXMMXMXAMAMXMMMXAMAAXXXAXAAAXSXMAMAMMMMSMXMAMSSMMASMMMXAXASXMXSASAAXAMXAXSMXSAMXASXMAM
SXMMSXAMSSSSSXSAMAAAMXAAAMMAMAMMSSSSSMMSAMMSAMXSAMSAXMAMXMAMXMSASXMSSMSSMSMSXMMSMAMSASMSSSMMMMXAMAMMAMSASAAXMXMAXAAAXASMSMMAASMXMAXAAMAMAXMM
XAMAMXMAXXMAMMMASMMMSSSMSMMXSXMMMAAMXAASAMAMXMXSAMMMAMXAAMASAAMASAAAAAAAAAXSASMAMAAXAMAAAAXMASMSSSMMAMMXSMMXAAAMSMMAMXMAMAXSSMXAMXSASMAXSMMX
SMMASMXMXXMMMASAMXSAAAXAMXMXSXSAMMMMSMMSXMASAAMSXMMSAMMSXSASMSMASMMMXSMMMMMSAMSXMXSMSMMMSSMMASAXAAASMMSXMAXMSXMXAXSXSMMXMXMMAMSXSAMMXMSAMASM
AXMAXAAMSMSXSASXSXAMMSMMMASMSASXMSAXXMASASASMSAMAMAMASXMXMAXMXMASXASAXMSXMAMXMAXMSXMMAMAMAMAXMXMMMMMSAMXSMMAXXSMMMAAAAXMASMSAMMAMXMSAAXMSXMA
MSMSXXAMAAMAMASAMMMMAXAAXXSAMXMAMSASMXASAMASAXMXAMMXXMXMMMMSSMMXXMASMSAAAMSMXMAXSAAMXSMMXAMAMXMXSAXXMXMAAXAMSAMASXMXMSMMAXASXMMASMAMMSSXMASM
XXAMASXSMXMAMMMMMAXMSSMMSSMXMMXMXXXMMMXSMMMMMMSSMSXAXSAMXAXXAASXSMAMXMMMSMMAXAMXXAXMAXAXSAMSAMXAXXSXMASXMASXMAMAMAXSSMXASMMMAXSAMXXXSMMAXAMA
SMAMAMAAXASXSAAASMSMMAASXMAAXAAMMMMSXSMXXAXAXMXAMSMMSAAMSMSSSMMAXMAMXMMXXAMMMMMMMSMMXSAMSXMASAMMSMAMAMXSMXXAMAMAXXMMAAMMXAAMAMMASXXXMAMSMXSM
AAAMAMMMMMXAMMXMSXMASXMSAMSMSSMSAAXAAXMASMMSXXSAMXAMAXMMMAMAXMMMMSMSSMSXMAMAAXXAAAAXAMAMXASAMMMMAXXSXMAAMAMASMSMSMMSMMMXSMMMSSSXMXMMMSMAXMAX
SSMSXXAAAXMMMSSMMXSAMXAXXMAMAMASXSMMSMMXMMMXMMSMMMXMAXXXMAMXMMXMAMMAAMAASXMSMSAMSMMMXMASMXMASASMMMASAMXAMXSAMMAXAMXXAXXXMMAXMXMXAMXSAMXAMMXM
MAMXASMMMXMMAAAMAMMASMMMSSMMAMMMXXAMXAXAXAASAAXAXAXMMSSMMMSMAXAMXSMSSMSXMAXAMXAMAXMSMSASAMXAMXMAASMSXMSXMXMASXSSMSSSMMXMASMMSAMMXMAXASMSSSMM
SAMMXMAASAMXMSXMAMSAMXAAXASMMMXMAXASMSMAMMSSMMXXMMAXAAMAAAAAMSMSXAAAMMXSAMXAXXAMXSMAAMAXMAMXSAMMMMAXAMXAAXSSMAXAXAAAXAXMAMXAMAMASMXMAMAAAMAX
SAMXXXMASAXMXXASAXXMASMMSMMMSSSMMSAMAMAXMSAMASXMMSSMMSSSMMSSXAAMXMMMSXSAMXSSMSSMAXMMMMXMXMSASXXMAAMSAMMSAMXXMSSMMSMMMSXMASMSSSMAMAXMMMMMSMMM
XAXSAMXMSXMSASAMXSAMAXAAXXAAMXAAAMXMAMXXXXASAMXAXAAAMAMXSXAXXMMXAMXMAMXMAMXXAAAMXSSXMXAMAXMXSAXSAMXMAXAXASMSAMXXAXASXMAMXMAXXASXMSAMXAAAAAXA
MSMMASXMSMXMASAMXXAMXMMMXSMSSXMMXMMSASMMMSXMAXMSMSSMMMSAMMMMXSASXSSMSMSXMXXMMMSAMXXAMSASMXMXMXMAAMASMMXSMAAMASAMSSMSASMMSMMMMMAXAXASASMMXSXX
MXAXAMAMMSAMXMASXSSMMSASAXMAMXSXMMAMAMAAAXMXSXAAAXAXAAMASMXSXMASAAAAAAMXXMMXAAAAMASMMMASAASXMMASMMMAAMXMMAXMASAMXXASAMMAAAAAAXMMAMAMAAXXSMMX
SMXMXMXAASMSAMXSXSAAXSAMXSMSMXSASMASASXMXSXAMMSMSMMSMXSAMAASAMXMMMMSMSMMAMXAMMSAMASXXXAMXMSAMAMMXXMXAMXMMSSMXSAMMMMMAXMXSSMMXXXMASAMXMAXAAXX
AASXMAMXMSASMMAXMXMMMMMMMMAAAAMAMMAXXSXMSMMASAMAAAXAAXMMSMAMXSAAAXXMXMMSASXSSXMAMSSXXMASAMSAMSMSMMXSMSXSAAAXAMAAXAXMAMSMMMMSMMXSASMXMXMSMSMX
MSMAASMSMMAMAMASAAXXXAAAMMSMSXMMMMMXMSAMAASAMMSSSSMMSMMAXXAMXSXSMSAMAXXSMMMAMXXAMXMXMSAXXMXAMMAAAMMAMXAMMSSMSSXMSXXMSMMAMMAAAAXMASXXAAXAMXAX
XAMXMMAXSMXSMMXAXMSMSMSXSXAAAASAMXMAMXASXMMASAAMAAXAMAMSSSMSAMXXASMMASAMXMMSMMSMSXMAMMSSSSSMMMSMSMAAXMXMXXMAXAXXXXXXMASMMMSSXMXMASMSSSSMMMSX
MMAXMMXMXSAMXMXMXMAAMAMASMMSMXSASASMSMMMMXSXMMSSSXMXSSMMAMXMMSASMMSMAMASXASAMAAAAXSAMSAXMAXAAAXXMMSMMSSMMSSSMSMSASMXSAMASXAXAMXMXMAXAXAAAAMM
AXSAMAXMMMMSAMMXASMMSAMAMAXAMMSAMASAAXSSSMXAMXMAMMSMAAXMXMXXXMMSAMXMSSXMMMSASMMSSXSXSAMXMAMMMMMXXAAAXXAAAAAAAXAMXMAASASAMMAXMXMASMSMMMSMMMSA
SMAASXSMAAASMMAMXSAAMAMMMXMMXAMXMMMXMASAAXSSMSXAAASASMMSSSMMSAMXMMXXXXAMAXSAMXMAMAMMSMXXMSXSASAAMSSSMSSMMMSMMMSMXMMMSXMAMMMMSAXAXMXMAAXAMAMX
XAMXMAAASXXSASMSAMMMSXSMMXMXMMMMSAMXXSXSMMSAAMXMMASAMXXAAAXXAAASMSXXMSMMSMMMSMMMSXMASXXXMAAMAMMSMAAAMAMAMMMAXXAXSXMMMMSSXXMASASXSMASMSSXMAMX
MSSMMSMMMMXSAMAMAXAAAASAAASASMSASASMMMAMXXXMMMXMMXMAMAMMSMMSSSMSAMXXMAMAXMAXMAXMXMMXSMSSMMSMAMAXMMSMMASMMAMSMSMSXMSAAMAMMSSMMXMAAMAXMMMMSMSM
AXAAAMASXXAMAMXMXAMSMXMMSXSASAAXSXXAAXAMSAMXAAAXAASMMAAXMAXAAAAMMMXMMAMASMSMSAMSAMXAMXAMAAXMXMASXAXXSMSASASAAAMXXASMSMMSAAAXSAMSMMSXSAAAAAAA
XSSMMSAMXMXSXMASXXXXXMAXXMMXMMMAXMSSMSASXSASXSSSSMXSSSSMSSMMSMMMAXMASXSMSAMXMXMSAXMASMSSMMSAMXXXMSMMAMXMSSSMSMSMXXMSXMXMMSSMSMMMSAMXSSSSMSMS""" 
    data = if useSample then sample else input 
  in 
    data |> String.split "\n" |> List.map (String.toList) |> Array2D.fromList

init : () -> (Model, Cmd Msg)
init _ =
  let 
    board = initBoard False
    model = { found = 0
            , board = board
            , highlighted = Set.empty
            , lastCommandText = "press play to start"
            , useSample = False 
            , counter = 0
            , debug = "" }
  in 
    (model, Cmd.none)

-- UPDATE

type Msg = Clear | Xmas | MasX | ToggleSample

updateClear : Model -> Model
updateClear model = { model | highlighted = Set.empty, found = 0 } 

-- getByPos : Pos -> Array2D Char -> Maybe Char
-- getByPos (x, y) board = 
--   Array2D.get y x board

findXmas : Array2D Char -> Pos -> (Pos -> Pos) -> List Pos
findXmas board xpos move = 
  let
    mpos = move xpos 
    apos = move mpos 
    spos = move apos 
    get (x, y) = Array2D.get y x board
    word = [ get xpos, get mpos, get apos, get spos ] |> List.filterMap identity 
  in
    if word == ['X', 'M', 'A', 'S'] then [ xpos, mpos, apos, spos ] else [] 

findXmasAllAround : Array2D Char -> Pos -> List Pos
findXmasAllAround board pos = 
  let
    nn = findXmas board pos (\(x, y) -> (x, y-1)) 
    nw = findXmas board pos (\(x, y) -> (x-1, y-1))
    ww = findXmas board pos (\(x, y) -> (x-1, y))
    sw = findXmas board pos (\(x, y) -> (x-1, y+1))
    ss = findXmas board pos (\(x, y) -> (x, y+1))
    se = findXmas board pos (\(x, y) -> (x+1, y+1))
    ee = findXmas board pos (\(x, y) -> (x+1, y))
    ne = findXmas board pos (\(x, y) -> (x+1, y-1))
  in
    List.concat [ nn, nw, ww, sw, ss, se, ee, ne ]

getAllPositions : Array2D Char -> List Pos
getAllPositions board = 
  let
    ys = List.range 0 (Array2D.rows board - 1)
    xs = List.range 0 (Array2D.columns board - 1)
  in 
    ys |> List.concatMap (\y -> xs |> List.map (\x -> (x, y)))

updateXmas : Model -> Model
updateXmas model = 
  let
    board = model.board 
    positions = board |> getAllPositions |> List.concatMap (findXmasAllAround board)
    charsPerXmas = 4
    found = (List.length positions) // charsPerXmas
  in
    { model | highlighted = (Set.fromList positions), found = found }

findMasX : Array2D Char -> Pos -> List Pos 
findMasX board (x, y) = 
  let 
    get (xDim, yDim) = Array2D.get yDim xDim board
    nwse = [ get (x-1, y-1), get (x, y), get (x+1, y+1) ] |> List.filterMap identity 
    swne = [ get (x-1, y+1), get (x, y), get (x+1, y-1) ] |> List.filterMap identity 
    isMas word = (word == ['M', 'A', 'S'] || word == ['S', 'A', 'M'])
  in 
    if isMas nwse && isMas swne then 
      [ (x, y), (x-1, y-1), (x+1, y+1), (x-1, y+1), (x+1, y-1) ]
    else 
      []

updateMasX : Model -> Model
updateMasX model = 
  let
    board = model.board 
    positions = board |> getAllPositions |> List.concatMap (findMasX board)
    charsPerMasX = 5
    found = (List.length positions) // charsPerMasX
  in
    { model | highlighted = (Set.fromList positions), found = found }

updateToggleSample : Model -> Model
updateToggleSample model = 
  let
    useSample = not model.useSample
  in
    { model | useSample = useSample, highlighted = Set.empty, found = 0, board = initBoard useSample } 

update : Msg -> Model -> (Model, Cmd Msg)
update msg model =
  case msg of
    Clear -> 
      (updateClear model, Cmd.none)
    Xmas -> 
      (updateXmas model, Cmd.none)
    MasX -> 
      (updateMasX model, Cmd.none)
    ToggleSample -> 
      (updateToggleSample model, Cmd.none)

-- SUBSCRIPTIONS

subscriptions : Model -> Sub Msg
subscriptions model = Sub.none

-- VIEW

toCharElement : Model -> Pos -> Html Msg 
toCharElement model (x, y) = 
    case Array2D.get y x model.board of 
      Nothing -> Html.text "?"
      Just ch -> 
        let
          str = String.fromChar ch 
        in
          if Set.member (x, y) model.highlighted then 
            (Html.strong [] [ Html.text str ]) 
          else 
            Html.text str 

view : Model -> Html Msg
view model =
  let
    board = model.board 
    ys = List.range 0 (Array2D.rows board - 1)
    xs = List.range 0 (Array2D.columns board - 1)
    nestedPositions = ys |> List.map (\y -> xs |> List.map (\x -> (x, y)))
    nestedElements = nestedPositions |> List.map (\positions -> positions |> List.map (toCharElement model))
    elements = nestedElements |> List.foldr (\a b -> List.append a (Html.br [] [] :: b)) []
    commandsStr = ""
    textFontSize = if model.useSample then "32px" else "12px"
  in 
    Html.table 
      [ Html.Attributes.style "width" "1080px"
      , Html.Attributes.style "font-family" "Courier New" ]
      [ Html.tr 
          [] 
          [ Html.td 
              [ Html.Attributes.align "center"
              , Html.Attributes.style "font-family" "Courier New"
              , Html.Attributes.style "font-size" "40px"
              , Html.Attributes.style "padding" "20px"]
              [ Html.div [] [Html.text "Advent of Code 2024" ]
              , Html.div [] [Html.text "Day 4: Ceres Search" ] ] ]
      , Html.tr 
          []
          [ Html.td 
              [ Html.Attributes.align "center"
              , Html.Attributes.style "padding-bottom" "10px" ]
              [ Html.text " ["
              , Html.a [ Html.Attributes.href "../../2024/"] [ Html.text "2024" ]
              , Html.text "] " 
              , Html.text " ["
              , Html.a [ Html.Attributes.href "../../2023/"] [ Html.text "2023" ]
              , Html.text "] "
              , Html.text " ["
              , Html.a [ Html.Attributes.href "../../2022/"] [ Html.text "2022" ]
              , Html.text "] "
              , Html.text " ["
              , Html.a [ Html.Attributes.href "../../2021/"] [ Html.text "2021" ]
              , Html.text "] "
              , Html.text " ["
              , Html.a [ Html.Attributes.href "../../2020/"] [ Html.text "2020" ]
              , Html.text "] "
            ] ]
      , Html.tr 
          []
          [ Html.td 
              [ Html.Attributes.align "center"
              , Html.Attributes.style "padding" "10px" ]
              [ Html.button 
                [ Html.Attributes.style "width" "80px", onClick Xmas ] 
                [ Html.text "XMAS" ]
              , Html.button 
                [ Html.Attributes.style "width" "80px", onClick MasX ] 
                [ Html.text "MAS-X" ]
              , Html.button 
                [ Html.Attributes.style "width" "80px", onClick Clear ] 
                [ Html.text "Clear" ] 
              , Html.button 
                [ Html.Attributes.style "width" "80px", onClick ToggleSample ] 
                [ Html.text (if model.useSample then "Input" else "Sample") ]
            ] ]
      , Html.tr 
          []
          [ Html.td 
              [ Html.Attributes.align "center"
              , Html.Attributes.style "background-color" "white" 
              , Html.Attributes.style "font-family" "Courier New"
              , Html.Attributes.style "font-size" "24px"
              , Html.Attributes.style "width" "200px" ] 
              [ 
                Html.div [] [ Html.text (String.fromInt model.found) ]
              , Html.div [] [ Html.text commandsStr ]
              ] ]
      , Html.tr 
          []
          [ Html.td 
              [ Html.Attributes.align "center"
              , Html.Attributes.style "background-color" "white" 
              , Html.Attributes.style "font-family" "Courier New"
              , Html.Attributes.style "font-size" textFontSize
              , Html.Attributes.style "padding" "10px"
              , Html.Attributes.style "width" "200px" ] 
              [ 
                Html.div [] elements
              ] ] ]
